import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import ReduxProvider from "@/providers/redux-provider";
import NextTopLoader from "nextjs-toploader";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import ReactToastProvider from "@/providers/toast-provider";
import fav from "../../public/icons/favicon.png";
import { hasCookie } from "cookies-next";
import { cookies } from "next/headers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Groooh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning={true}
        className={`font-Suisse bg-pr ${
          cookies().get("localConcent")?.value === undefined
            ? "overflow-hidden"
            : ""
        }`}
      >
        <NextTopLoader
          color="#e3ff00"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <AppRouterCacheProvider>
          <ReactToastProvider>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              <ReduxProvider>{children}</ReduxProvider>
            </ThemeProvider>
          </ReactToastProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
